### ISSUE TITLE
pecl-event incompatible with Laravel

### ISSUE THREAD

**Issue by TKr** [chialab/docker-php#103]
Bug ? Notice ?

pecl-event registers class Event::class
laravel has own "Facade" system and register Event as `Illuminate\Support\Facades\Event::class`
but can not, pecl-event has already done this

Laravel's `Event::dispatch(something)` ends with error.

**Comment by fquffio** [comment]
Hi @TKr, sorry for the issue. Can you help me reproduce? Can you please write which libraries are you installing and their versions? Maybe try attaching your `composer.json` redacting anything that you don't want to share…?
