### ISSUE TITLE
PHP 8.1 Minor Versions

### ISSUE THREAD

**Issue by jjarolim** [chialab/docker-php#104]
Hi!

**First of all - thanks for your cool packages!** 
It's a breeze starting projects with them: so really thanks alot!

I'd have one question though: 

According to your documentation, you do a rebuild of the images every time a new PHP release is out, but if I pull `chialab/php8.1-apache`, I get an image containing `PHP 8.1.2` instead of `PHP 8.1.12`, which would be the [current release](https://hub.docker.com/_/php/tags?page=1&name=8.1).

Unfortunately, I'd need to use a library requesting PHP > 8.1.10

Could you please point me to the right direction?
Am I doing something wrong?

**Comment by le0m** [comment]
Scheduled pipeline has runned with success, I'll consider this issue resolved.

Comment again if you're having any issue!
