### ISSUE TITLE
Ftp extension missing in image -> chialab/php-dev:8.2

### ISSUE THREAD

**Issue by vetjun** [chialab/docker-php#121]
Hi, we use chialab/php-dev:8.2 image in our development environments for unittest pipelines.
our composer json like
.....
"ext-json": "*",
        "ext-ftp": "*",
        "ext-curl": "*",
        "ext-pdo": "*",
        "ext-soap": "*",
        "ext-intl": "*",
        "ext-simplexml": "*",
        "ext-iconv": "*",
        "ext-zip": "*",
....
When pipeline is started, it gives this error ->
"$ php composer.phar install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.
  Problem 1
    - Root composer.json requires PHP extension ext-ftp * but it is missing from your system. Install or enable PHP's ftp extension.
To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/conf.d/docker-php-ext-amqp.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-bz2.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-calendar.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-exif.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gd.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gettext.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-imagick.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-ldap.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pgsql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-redis.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-soap.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sockets.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-xsl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
    - /usr/local/etc/php/conf.d/xx-php-ext-event.ini
    - /usr/local/etc/php/conf.d/xx-php-ext-memcached.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-ftp` to temporarily ignore these required extensions.
ERROR: Job failed: exit code 1 "

2 days ago some changes committed and I can see commits about FTP.
Can it affect this issue?

**Comment by le0m** [comment]
This image does not come with FTP extension, you should be able to install it running `install-php-extensions ftp`
