### ISSUE TITLE
Re-think CI for dev images

### ISSUE THREAD

**Issue by fquffio** [Chialab/docker-php#13]
At the present status, Travis CI jobs for dev images build such images on top of `chialab/php` images pulled from Docker Hub.

This causes problems when adding features to base `chialab/php` images, since tests will very likely fail for `chialab/php-dev` images (see #11 and #12). The CI for dev images must be re-thought.

**Comment by Nemo64** [comment]
A simple solution would be to simply auto generate the docker files and not include the main image in the dev image but creating them all from scratch. Dockers caching mechanism should be able to catch if 2 commandos on 2 images are the same so there is no giant overhead of re-downloading the whole thing just for the dev image.

If you wan't i can try to setup such a build process.

**Comment by fquffio** [comment]
I was thinking of another solution: simply test dev images in the same jobs as the main ones. This would reduce the total number of jobs, but each job would take slightly longer. It should be pretty straightforward, I'll try to set something up in the afternoon. In the meanwhile, the PR can be merged anyways.
