### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by fquffio** [Chialab/docker-php#18]
PHP 7.2 is now in RC phase. According to the [official timetable](https://wiki.php.net/todo/php72) it should become GA by the end of November.

We should save the date and add 7.2 images. Official Docker images for the RC releases are available, so we can use those as a starting point in the meanwhile.

**Comment by Nemo64** [comment]
What's the status on this? The travis build tells me that xdebug is the issue?

**Comment by Nemo64** [comment]
Thanks for your continuing maintenance, those images really save a lot of compile time :)
The images aren't pushed to the public hub yet, right?
https://hub.docker.com/r/chialab/php/tags/

**Comment by fquffio** [comment]
Ouch! You're right! I need to add configuration to Docker Hub… 😞  Sorry for that, I'll trigger the new builds in a few minutes!

**Comment by fquffio** [comment]
Images should now be available on Docker Hub for pull. The automated build should have correctly been set up. Thanks @Nemo64 for reporting!

If there's still something wrong, anybody feel free to comment again or open a new issue.

**Comment by Nemo64** [comment]
Awesome, thanks 👍
