### ISSUE TITLE
Memcached Server

### ISSUE THREAD

**Issue by soromamadou** [Chialab/docker-php#37]
Hello,
you have done a great job. I run into an issue. I can't use memcached. I think this is due to the fact that it is'nt installed via your dockerfiles. I'am using php7.2-fpm dockerfile.
Could you please check it 
Thanks
?

**Comment by fquffio** [comment]
Hi @soromamadou !

Thanks for your interest in this project. The `memcached` extension should be already installed. 🤔 I have made a simple test, and everything looks fine to me. Here's what I've tried.

```
# First, I've started a Docker container with Memcached:
$ docker run -d --rm --name memcached memcached

# Then, I've started a Docker container from the `chialab/php:7.2-fpm` image and used PHP's interactive console.
$ docker run -it --rm --name php --link memcached:memcached chialab/php:7.2-fpm php -a
Interactive shell

php > $mem = new Memcached();
php > $mem->addServers([['memcached', 11211]]);
php > $mem->set('foo', 'bar');
php > var_dump($mem->get('foo'));
string(3) "bar"
```

Could you try to explain what you've been trying that did not work as expected?

**Comment by fquffio** [comment]
Hey @soromamadou , any updates on this? Have you been able to sort it out?

**Comment by soromamadou** [comment]
HI, Sorry for late response.

It works as expected. Thanks for all.
