### ISSUE TITLE
Memory allocation error but no php.ini how to modify memory setting

### ISSUE THREAD

**Issue by manzurshaikh** [Chialab/docker-php#42]
2018-09-18 17:20:08 Error: Fatal Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in [/var/www/html/vendor/cakephp/cakephp/src/Database/Statement/PDOStatement.php, line 71]
Request URL: /admin/recons/upload
Referer URL: https://xx.com/admin/recons/upload
Client IP: 211.24.107.194
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE/src/Error/BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE/src/Error/BaseErrorHandler.php, line 104
[main] - [internal], line ??

root@569d9c5af48f:/var/www/html# php --ini
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
/usr/local/etc/php/conf.d/docker-php-ext-bz2.ini,
/usr/local/etc/php/conf.d/docker-php-ext-calendar.ini,
/usr/local/etc/php/conf.d/docker-php-ext-exif.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gettext.ini,
/usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-ldap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini,
/usr/local/etc/php/conf.d/docker-php-ext-memcached.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pgsql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-redis.ini,
/usr/local/etc/php/conf.d/docker-php-ext-soap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini

**Comment by Nemo64** [comment]
Use a `Dockerfile` and define your settings like something like this:

```
RUN echo 'max_execution_time=240' >> /usr/local/etc/php/conf.d/php.ini \
 && echo 'memory_limit=1G' >> /usr/local/etc/php/conf.d/php.ini
```

**Comment by manzurshaikh** [comment]
FROM php:7.1-apache
MAINTAINER dev@chialab.it

# Install PHP extensions and PECL modules.
RUN buildDeps=" \
        default-libmysqlclient-dev \
        libbz2-dev \
        libmemcached-dev \
        libsasl2-dev \
    " \
    runtimeDeps=" \
        curl \
        git \
        libfreetype6-dev \
        libicu-dev \
        libjpeg-dev \
        libldap2-dev \
        libmcrypt-dev \
        libmemcachedutil2 \
        libpng-dev \
        libpq-dev \
        libxml2-dev \
    " \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y $buildDeps $runtimeDeps \
    && docker-php-ext-install gettext \
    && docker-php-ext-install bcmath bz2 calendar iconv intl mbstring mysqli opcache pdo_mysql pdo_pgsql pgsql soap zip \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
    && docker-php-ext-install ldap \
    && docker-php-ext-install exif \
    && pecl install memcached redis \
    && docker-php-ext-install mcrypt \
    && docker-php-ext-enable mcrypt \
    && docker-php-ext-enable memcached.so redis.so \
    && apt-get purge -y --auto-remove $buildDeps \
    && rm -r /var/lib/apt/lists/* \
    && a2enmod rewrite \
    && a2enmod ssl \
    && a2enmod headers
####memory limit#######
RUN echo 'max_execution_time=240' >> /usr/local/etc/php/conf.d/php.ini \
 && echo 'memory_limit=1G' >> /usr/local/etc/php/conf.d/php.ini
# Install Composer.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && ln -s $(composer config --global home) /root/composer
#ENV PATH $PATH:/root/composer/vendor/bin
#ENV APP_HOME /var/www/html

**Comment by manzurshaikh** [comment]
@Nemo64  i don't have php.ini inside the docker how do i do this?

**Comment by manzurshaikh** [comment]
Thanks, issue has been resolved 👍
