### ISSUE TITLE
Set env COMPOSER_ALLOW_SUPERUSER to 1

### ISSUE THREAD

**Issue by Toflar** [Chialab/docker-php#44]
Hey, cool image, thank you!

Using it to run my unit tests that need composer and the zip extension.
Do you mind adding `ENV COMPOSER_ALLOW_SUPERUSER 1` to the `Dockerfile`? This will disable the composer warning, see https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

**Comment by fquffio** [comment]
Hey @Toflar ! Sorry I forgot to answer you sooner. Thanks for your interest in this project!

Seems a good idea… just wondering if there could be any unintended side effects…? 🤔

**Comment by Toflar** [comment]
Nah, it just disables the warning that‘s all :)
