### ISSUE TITLE
Add unzip

### ISSUE THREAD

**Issue by Toflar** [chialab/docker-php#48]
Would be great if `unzip` could be added to the image. That way composer will unzip the packages faster and more reliably (and the warning about it would be gone ;-)).

**Comment by fquffio** [comment]
Hi @Toflar , sorry it took me so long to triage your issue. I had read it but then I forgot… 😞

I agree it would be a good enhancement to the image. I personally prefer to use multi-stage builds to reduce size of the resulting image, but I agree that it could be useful, at least for "base" images (those that aren't neither `-apache` nor `-fpm`).

Would that be enough? 🤔

**Comment by Toflar** [comment]
Well, basically any image where you'd do something like `RUN composer install` in would benefit so at least for `-apache` it would probably be relevant as well. So you can quickly package a web app. 
And I'm a fan of reduzing size too but we're talking like 500kb here :)
