### ISSUE TITLE
Update XDebug for PHP 7.3

### ISSUE THREAD

**Issue by fquffio** [chialab/docker-php#49]
PHP 7.3 development images are using a beta version of XDebug 2.7.0. As soon as a stable version is released, they should be updated.

See <http://pecl.php.net/package/xdebug>

**Comment by Toflar** [comment]
Still no tag on Docker Hub 😢  Is it related to xdebug? If so, 2.7.0 stable was released 6 days ago 🎉

**Comment by fquffio** [comment]
Hi @Toflar ! I've opened a PR.

**Comment by Toflar** [comment]
Weehee, thank you! Looking forward to the new image tag 😄

**Comment by fquffio** [comment]
Yeah, the fact that the tag is missing is a bit weird, actually… Travis should build & upload images to Docker Hub, but probably something's not working. 🤔

**Comment by Toflar** [comment]
Yeah somehow nothing is shown on Docker Hub.

**Comment by fquffio** [comment]
Images should be built on Docker Hub… I got confused with another project where we build and push from Travis. Still, it's not working anymore.

I've opened #53 and I'll take care of it as soon as possible!
