### ISSUE TITLE
Error: [Error] Call to undefined function App\Shell\ssh2_connect()

### ISSUE THREAD

**Issue by manzurshaikh** [chialab/docker-php#50]
Hi Guys

please help 
getting below error 
2019-01-11 10:35:02 Error: [Error] Call to undefined function App\Shell\ssh2_connect() in /var/www/html/src/Shell/OfflineDepositShell.php on line 24

i have already tried 
&& apt-get install -y libssh2-1-dev libssh2-1 \
&& pecl install ssh2 \
&& docker-php-ext-enable ssh2 

but it's not working
ERROR: Service 'cakephp' failed to build: The command '/bin/sh -c apt-get install -y git libssh2-1 &&     pecl install ssh2 &&     docker-php-ext-enable ssh2' returned a non-zero code: 1

Thanks

**Comment by fquffio** [comment]
Hi @manzurshaikh ! Which image are you building upon?

I've tried with the following `Dockerfile`:
```dockerfile
FROM chialab/php:latest

RUN apt-get update \
  && apt-get install -y libssh2-1-dev libssh2-1 \
  && pecl install ssh2-1.1.2 \
  && docker-php-ext-enable ssh2
```

Trying to build such image (`docker image build -t my/tag my/path/`) I get exit code 0, and `docker run --rm my/tag php -m | grep ssh` outputs `ssh2` as expected. 😉

**Comment by fquffio** [comment]
My apologies, but I'm closing this issue as two months have passed without any response. Feel free to open another issue should the problem persist.
