### ISSUE TITLE
Images are not being built on Docker Hub

### ISSUE THREAD

**Issue by fquffio** [chialab/docker-php#53]
Images are not being built on Docker Hub. This might be a good chance to push the very same image that has been built (and tested!) on Travis CI.

**Comment by blakethepatton** [comment]
Probably, related... I'm getting the following error when trying to pull down php 7.3-fpm

```shell
$ docker pull chialab/php:7.3-fpm
Error response from daemon: manifest for chialab/php:7.3-fpm not found
```

**Comment by Toflar** [comment]
Ping @fquffio

**Comment by le0m** [comment]
This has been solved, images are deployed with Travis.
