### ISSUE TITLE
Adding Prestissimo to php-dev images

### ISSUE THREAD

**Issue by Lelenaic** [chialab/docker-php#55]
As composer is very slow by default, can you add the Prestissimo plugin in the dev images? (https://github.com/hirak/prestissimo) It is a very efficient composer speed plugin which is very usefull when they are many packages to download.

**Comment by Nemo64** [comment]
You could share your composer home directory with your host or put it in a volume. That would allow you to cache downloads and you could also allow you to install a global package in it like prestissimo.

**Comment by le0m** [comment]
I'm currently evaluating this, not only for dev images.

I've been using Prestissimo plugin for over an year in multiple projects, and has been a blessing for CI/CD pipelines.
Since we're already installing composer, I don't see reasons not to add this.
