### ISSUE TITLE
Script to install extensions

### ISSUE THREAD

**Issue by mlocati** [chialab/docker-php#60]
This is not strictly an issue, but rather a suggestion.

I've written a [well tested a script](https://github.com/mlocati/docker-php-extension-installer) that automatically installs APT (on Debian) and APK (on Alpine) dependencies, so that (for example) you can write `install-php-extensions gd` to easily install the php GD extension.

Since for this `chialab/docker-php` you too have to check these dependencies, what about using that script instead?

**Comment by le0m** [comment]
Hello and sorry for the delay, I was away for holidays.

I saw your script being mentioned by tianon in a docker issue I was reading, this could be a good opportunity for using it. BTW awesome script :+1: 

Did a rapid test in local and this also shrank our `5.6-apache` image size down to ~440 MB, which is a nice bonus :smile:  I'll push a PR by the end of this week.

PS: happy new year!

**Comment by le0m** [comment]
PR has been merged, thanks again for your work :+1:

**Comment by mlocati** [comment]
PS: I recently added support for PHP 5.5 to the `install-php-extensions` script
