### ISSUE TITLE
"Cannot load Xdebug - it was already loaded"

### ISSUE THREAD

**Issue by DavidCarrington** [chialab/docker-php#64]
I've only tested against chialab/php-dev:7.4

`php --ini` reports two different files trying to load xdebug, xdebug.ini and docker-php-ext-xdebug.ini, so these error is appearing in various output.

Can one of these references be removed? It looks like xdebug.ini is created by the Dockerfile within this project.

**Comment by le0m** [comment]
Hello and thanks for reporting the issue.

This is caused by #61 on versions 5.6+, I'll fix it asap.

**Comment by le0m** [comment]
Referenced commit fixes the issue, I'm closing this.
