### ISSUE TITLE
The docker image of chialab/php:7.4-apache needs a rebuild to use latest 2.0.x composer version.

### ISSUE THREAD

**Issue by pazion** [chialab/docker-php#72]
The current 2.0x version has an issue with the package laminas-dependency-plugin:

$ composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --no-dev --no-autoloader

Loading composer repositories with package information
Installing dependencies from lock file
                                                                                   
  [ErrorException]                                                                 
  assert(): assert($rewriter instanceof DependencySolvingCapableInterface) failed  

When updating the composer version this is resolved.

**Comment by fquffio** [comment]
Thank you for reporting this! I'm triggering a rebuild straight away.

I was also wondering whether we should ship separate images for Composer 1.x and 2.x, or have both like `composer1` and `composer2`, with `composer` being a symlink to the latter. But I'm opening another issue for this.

**Comment by fquffio** [comment]
It was already mentioned in the linked issue, but the build process is temporarily broken due to Composer 2 rightfully refusing to install `hirak/prestissimo` plugin. Once the fix will be applied, this issue can be closed too.
