### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by le0m** [chialab/docker-php#75]
travis-ci.org will be closed down on december 31, public repos are required to migrate to travis-ci.com before that date (see [newsletter](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom)).

As an alternative, we could switch to GitHub Actions.

**Comment by le0m** [comment]
I tested GitHub Actions (see [here](https://github.com/le0m/docker-php/actions/runs/342641061)), here's my thoughts:
- it's faster than Travis, the pipeline took 14 minutes to build and test all image tags
- if a single job fails you can't re-run only that like any sane CI solution, you have to re-run the whole pipeline

**Comment by fquffio** [comment]
Agree that Travis isn't the solution to go anymore.

As an alternative, I propose also evaluating Azure DevOps Pipelines, which are of course free for open source. If I'm not wrong, GitHub Actions are basically a wrapper around that platform, and syntax is pretty much similar. I'll take a look at that and open a test branch in the afternoon.
