### ISSUE TITLE
Support for PHP 8.0.0

### ISSUE THREAD

**Issue by ad-m** [chialab/docker-php#77]
>  The PHP development team announces the immediate availability of PHP 8.0.0. This release marks the latest major release of the PHP language.

– https://www.php.net/archive/2020.php#2020-11-26-3

**Comment by ad-m** [comment]
Blocked by docker-library/php#1093

**Comment by ilya-realforce** [comment]
Bump, seems that `php` image supports 8.0 now.

**Comment by le0m** [comment]
Hello, I'm currently waiting on `pdo_sqlsrv` and `sqlsrv` to get out of beta https://github.com/Microsoft/msphpsql/releases (which is also making the build fail)

**Comment by 7elix** [comment]
The https://github.com/docker-library/php/pull/1090 seems to be solved. How can we support your initiative?

**Comment by ad-m** [comment]
@7elix , see #80 for information about missing & blocking release of `sqlsrv` driver and see microsoft/msphpsql#1154 for further release plans and required help.

**Comment by vanam** [comment]
Any update?

**Comment by le0m** [comment]
Thanks for the reminder, I was checking `sqlsrv` weekly and didn't notice they [released 5.9.0](https://github.com/microsoft/msphpsql/releases/tag/v5.9.0) with PHP 8 support 2 days ago.

**Comment by vanam** [comment]
Could you publish it through docker hub? I don't see it there (https://hub.docker.com/r/chialab/php-dev/tags) Thx.

**Comment by ad-m** [comment]
@vanam, no, it's not possible at that moment. Blocked by #78 . See also comments in https://github.com/chialab/docker-php/commit/48dd3cbc498bb1ef3b5aaba5a5f10e4af964bb50#comments .

**Comment by ENM1989** [comment]
> @vanam, no, it's not possible at that moment. Blocked by #78 . See also comments in [48dd3cb#comments](https://github.com/chialab/docker-php/commit/48dd3cbc498bb1ef3b5aaba5a5f10e4af964bb50#comments) .

Seems doable now, because #78 was merged.

**Comment by pulponair** [comment]
Then do it :) 👏

**Comment by le0m** [comment]
It's done 😃
