### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by halloei** [chialab/docker-php#91]
> The PHP development team announces the immediate availability of PHP 8.1.0. This release marks the latest minor release of the PHP language.

– https://www.php.net/archive/2021.php#2021-11-25-1

**Comment by halloei** [comment]
@le0m Maybe this chance should be used to drop Composer 1, as it's deprecated?

**Comment by le0m** [comment]
Sorry for the delay, in the next weeks I'll be busy with work & holidays so I won't be able to look into this 😞 

I opened a PR, pipelines currently fail on build of `-dev` image because it expects to have the base PHP 8.1 image, which isn't pushed to DockerHUB yet.

**Comment by danakishi** [comment]
Hi @le0m 
I propose to correct GitHub Actions workflow for building dev images after building main image

My PR https://github.com/chialab/docker-php/pull/93

Thanks

**Comment by le0m** [comment]
Thanks for the PR and sorry for the delay 👍🏼
